import { Router, type IRouter } from "express";
import { getAllPackets, getThreats, getThreatLevel, getComplianceReport } from "../lib/simulator.js";
import { computeKillChain } from "../lib/killchain.js";

const router: IRouter = Router();

router.get("/report/forensic", (_req, res) => {
  const now = new Date();
  const packets = getAllPackets();
  const threats = getThreats();
  const level = getThreatLevel();
  const compliance = getComplianceReport();
  const killChain = computeKillChain(packets);

  // Top threat IPs
  const ipMap = new Map<string, { count: number; ports: Set<number>; country: string; severity: string }>();
  for (const p of packets.filter(p => p.is_anomaly && p.is_external)) {
    const ip = p.src_ip;
    const existing = ipMap.get(ip) || { count: 0, ports: new Set(), country: p.country, severity: p.severity };
    existing.count++;
    existing.ports.add(p.dst_port);
    if (p.severity === "CRITICAL") existing.severity = "CRITICAL";
    else if (p.severity === "HIGH" && existing.severity !== "CRITICAL") existing.severity = "HIGH";
    ipMap.set(ip, existing);
  }
  const topIps = [...ipMap.entries()].sort((a, b) => b[1].count - a[1].count).slice(0, 10);

  const iptablesRules = topIps.map(([ip]) => `iptables -I INPUT -s ${ip} -j DROP  # Threat IP`).join("\n");

  const activeMitre = killChain.filter(s => s.status !== "INACTIVE");

  const report = `# AegisView Forensic Incident Report

**Generated:** ${now.toISOString()}
**Analysis Window:** Last ${packets.length} packets captured

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Packets Analyzed | ${level.packets_analyzed} |
| Anomalies Detected | ${threats.length} |
| Threat Level | ${level.score}/100 — **${level.label}** |
| Compliance Risk | **${compliance.risk_rating}** |
| Anomaly Rate | ${compliance.anomaly_rate_percent.toFixed(2)}% |

---

## Threat Timeline

${threats.slice(0, 20).map(t =>
  `- **${t.timestamp.replace("T", " ").substring(0, 19)}** | ${t.src_ip} → ${t.dst_ip}:${t.dst_port} | [${t.severity}] ${t.reason}`
).join("\n")}

---

## Compliance Violations

${compliance.rules_triggered.map(r =>
  `### ${r.framework} — ${r.id} [${r.severity}]\n**Rule:** ${r.description}\n**Evidence:** ${r.evidence}`
).join("\n\n")}

${compliance.rules_triggered.length === 0 ? "_No compliance violations detected._" : ""}

---

## Top Threat IPs

| IP | Country | Packets | Ports Targeted | Classification |
|----|---------|---------|----------------|----------------|
${topIps.map(([ip, s]) =>
  `| ${ip} | ${s.country} | ${s.count} | ${[...s.ports].slice(0, 5).join(", ")} | ${s.severity} |`
).join("\n")}

---

## MITRE ATT&CK Coverage

${activeMitre.length === 0 ? "_No MITRE ATT&CK stages activated._" : activeMitre.map(s =>
  `### ${s.stage} (${s.id}) — **${s.status}** [${s.confidence}% confidence]\n${s.evidence}`
).join("\n\n")}

---

## Recommended Firewall Rules

\`\`\`bash
# Block identified threat IPs
${iptablesRules || "# No external threats identified"}

# Block sensitive port exposure
iptables -I INPUT -p tcp --dport 23 -j DROP   # Block Telnet
iptables -I INPUT -p tcp --dport 3389 -j DROP -m comment --comment "Block external RDP"
iptables -I INPUT -p tcp --dport 445 -j DROP  # Block SMB external
\`\`\`

---

## Risk Rating: ${compliance.risk_rating}

_Generated by AegisView v2.0 — Real-Time SOC Dashboard_
`;

  const timestamp = now.toISOString().replace(/[:.]/g, "-").substring(0, 19);
  res.setHeader("Content-Type", "text/markdown");
  res.setHeader("Content-Disposition", `attachment; filename="aegisview_report_${timestamp}.md"`);
  res.send(report);
});

export default router;
